### ISSUE TITLE
Investigate Shopify technology as buy button

### ISSUE THREAD

**Issue by DavidMulhern** [DavidMulhern/PPIT_SN_DM#3]

**Comment by codeBySvet** [comment]
Focus: If we decide on making a website for hobbies, we would want to include a way for users to easily purchase the items mentioned in any given hobbies instructions. 

Considerations: Shopify is an online e-commerece platform. It has the functionality on the backend to facilitate real world financial transactions along with stock management for items. It would be a great service to use in order to allow users of the website to easily purchase items for a hobby.

**Comment by codeBySvet** [comment]
I am currently doing an inital investigations on the viablility of intergrating Shopify and its SDK into a website we build from the ground up. I expect to have to create access tokens to access the Shopify side, along with importing certain frameworks from Shopify.

This is currently being investigated.

**Comment by codeBySvet** [comment]
Based on my investigation so far, it seems possible to use Shopify as a third party intergration to facilitate adding a "add to cart" button/s per web page. There is good documentation on the steps to follow. If implemented, it allows for a drawr style cart to slide out from the right edge of a display to show the user what is in their cart thus far (without having to leave the website until actually checking out).

The overall process does however have some nuances. Any given product that needs to have an add to cart button must first be created on the backend of a Shopify store, before it can have an add to cart button generated. The add to cart buttons thus far appear to have to be hard coded one by one also, which will make editing a webpage a very tedious if the products need to be changed. 

Thus far, we have not made a final descision of this project will be based on a website for hobbies or a social media app. If we go ahead with making the hobbies website, I will look to get a working version of Shopify implemented on a testing enviroment first. 

The overall feature of being able to buy items from the hobbies website would not be a necessity, but would be a very attractive addon. Hence, it is not a top priority at this time.

**Comment by codeBySvet** [comment]
We have decided to create a website which works on the premise of a kanban board.

As we have decided to develop a website which does not align with the need for buy button functionality, I will be closing off this milestone.
