### ISSUE TITLE
Drag and Drop Functionality

### ISSUE THREAD

**Issue by codeBySvet** [DavidMulhern/PPIT_SN_DM#33]
A central aspect of this project is having drag and drop functionality. The idea is that there will be around 3 or 4 columns on the main page which lists all created cards. A user should be able to drag and drop cards between different columns. 

This will open up some complexity in how we decide to store the cards. For example, do we want to call a POST request to the server which saves the updated layout of the cards every single time a card is taken out of one column and into another. Or else, do we want to save it just once at the end of a user interacting with the website (for example to call a POST when the browser tab is closed). 

Firstly, we are going to prioritise to just adding the general drag and drop functionality. Afterwards once that is working we will iron out how to handle the saving to the databse any time the order of the cards is changed.

**Comment by DavidMulhern** [comment]
I have created a separate repository as a "sandbox" to test out React Beautiful D&D.

This has been purposely done just to ensure while testing and working with this new library it does not confuse or interfere with our current code, just until we get used to the library and its functionality. 

Currently, the code within is the basic functionality of beautiful D&D. Once column, with four moveable components. There is still more to work on with this sandbox but I felt it was best to upload the current version while the code is purely focused on functionality without major styling or complexity.

Please find this at the repository below:
https://github.com/DavidMulhern/DnD_Sandbox

**Comment by DavidMulhern** [comment]
A new sandbox has been made. Previous drag and drop version did not allow user manipulation, Svetlin and I needed to spend a day to rework the code base. 

In this repo you will find a new version of the "work in progress" project. In the navigation bar there is a tab makes "User Board".
In here the user can create columns and cards. Both columns and cards are moveable!

https://github.com/DavidMulhern/DnD_UserAdds

**Comment by DavidMulhern** [comment]
Complete.

Since the last comment there has been a tremendous amount of work and effort put into the below github repository:

https://github.com/DavidMulhern/DnD_UserAdds

This is the location of the final version of the code. Drag and drop is fully functional, it's state in the application is persisted to mongoDB and it also uses rich text editor for a clean and professional feeling cards. Please follow readme guid lines should you desire to try this product or view the code.
