### ISSUE TITLE
Data Storage (Back End)

### ISSUE THREAD

**Issue by DavidMulhern** [DavidMulhern/PPIT_SN_DM#5]

**Comment by codeBySvet** [comment]
Focus: Deciding the best type of database to store the data we need to store all the data of this project

Data to be stored: Content (text and images), Login details(text)

Considerations: Ideally we would like to use a single database to hold all the data. This promotes a clean and clear design on the backend. Seeing as the data needed to be stored will vary by type, we are primarily investigating unordered database types. 

MongoDB is a source-available cross-platform document-oriented database program. Classified as a NoSQL database program, MongoDB uses JSON-like documents with optional schemas. This initally seems like a good option and would allow for MERN based development.  

However, other options are currently also being explored.

**Comment by codeBySvet** [comment]
We have gone ahead with using MongoDB. 

It uses a json-similar format to store documents. This format directly maps to native objects in React(and other modern languages), making it a natural choice. Its online interface and the code needed to implement the connection to our project are relatively straight forward.

We have created an account with MongoDB and have setup a databse with them for the project.
