### ISSUE TITLE
Login Feature research

### ISSUE THREAD

**Issue by DavidMulhern** [DavidMulhern/PPIT_SN_DM#6]

**Comment by codeBySvet** [comment]
Focus: Regardless if this project goes ahead with creating a website for hobbies, or a social media application for pets, in both cases we will require that users can signup and login. We are currently investigating the complexity of having a login feature and how best to implement it.

Considerations: 
* Users must be able to Sign-up
* Users must be able to login
* False login credentials do not allow the user to log in
* Correct login credentials does log in the user
* Login credentianals must be stored in a databse

**Comment by DavidMulhern** [comment]
Login component has been implemented.

Currently working on functionality between mongoDB and user input via the front end. WIP

**Comment by DavidMulhern** [comment]
This has been completed, tested and working as intended. Front end now has user verification that communicates with the database stored on MongoDB.
