### ISSUE TITLE
Technology/Frameworks/Languages research

### ISSUE THREAD

**Issue by DavidMulhern** [DavidMulhern/PPIT_SN_DM#7]

**Comment by codeBySvet** [comment]
Focus: Deciding on what language and framework would best suit the project requirements. 

Considerations: 
* Knowledge/expertise of the developers
* Documentation quality of languages
* Potential limitations of one language over another
* Intended use of Frameworks

**Comment by DavidMulhern** [comment]
React drag and drop - react-beautiful-dnd

We are considering using the react-beautiful-dnd library to allow user to freely drag and drop components of the UI.
We feel this is something rarely seen, makes for an interactive user experience and can be implemented in many ways in different applications. 

Research is ongoing but we feel this is something we would like to work with.

**Comment by DavidMulhern** [comment]
Below is the full and final list of technologies and libraries used.

Technologies used:
• React - Front end UI.
• Express JS - Back-end framework for HTTP functionality.
• Node - Back-end runtime environment for JS.
• Mongo - Database.

Libraries used:
• cors – Middleware to allow HTTP transactions.
• jsonwebtoken - Implemented both client and server side, used for token exchange and verification.
• mongoose – Database connection
• jwt-decode - Token decode.
• bcryptjs - Password encryption.
• react-beautiful-dnd – Creates and environment where components can be manipulated by the user.
• uuid – Used to generate unique keys for cards.
• react-router-dom – Application routing.
• @ckeditor/ckeditor5-react @ckeditor/ckeditor5-build-classic – Used for rich text editor on cards.
• React-bootstrap – Styling.
• @mui/icons-material – Styling.
• @material-ui/styles – Styling.
• @emotion/styled – Styling.
• @emotion/react – Styling.
• @material-ui/core@next – Styling.
