### ISSUE TITLE
Concept - Website vs App

### ISSUE THREAD

**Issue by codeBySvet** [DavidMulhern/PPIT_SN_DM#8]
Focus: The main aim is to determine if this project will be created as an app or a website. The following two ideas have been proposed:

Website: A website which will act as a hub for creatives. Users can go onto the website and browse a library of content centered around hobbies. For example: How to plant flowers in a garden. A comprehensive list of instructions/guides and where to buy the tools needed will be offered. It is essentially a one stop spot for people looking to get into new hobbies. 
Inspiration - https://www.instructables.com/

App: Recreate a social media app, but for pets. Something like facebook or Instagram where users create profiles. They can then share images and posts. Users will have their own personal profile feed, and a main feed. The idea is that this will be a social media platform for pets and hence it will be leaning more so on visual elements rather than text. Inspiration - https://www.instagram.com/

Considerations: These two ideas are the final options we have decided on. Myself and David are in constant communication to determine which we feel more excited to do. Also taking into consideration the inner functionality required for each. A comprehensive list of expected functionality is being worked on for each idea which will be brought to our Mentor to help make a final descision between the two.

**Comment by codeBySvet** [comment]
David has created Mock ups for the front end and overall layout of both ideas. We will be presenting both to our assigned mentor very shortly to make a final decision.

**Comment by DavidMulhern** [comment]
We have decided to go with an application which will allow for dynamic components. 
This application will reflect as a type of "Kanban" board. The user will be able to drag and drop components (which will be displayed as cards).
These cards will contain text and images. We also intend to implement scalable sizes for these cards/components.
